name: Package CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install black pytest-cov
    - name: Test with pytest
      run: |
        pytest --cov
    - name: Check format with black
      run: |
        black --check .
